  delimiter //
CREATE TRIGGER insertArticles
AFTER INSERT ON MED_ARTICLES
FOR EACH ROW 
BEGIN

INSERT INTO MED_ARTICLES_H (FK_ARTICLE, AUTHOR, TITLE, CONTENT, HEADLINE, FK_EDITOR, MODIFIED_DATE)
  VALUES(NEW.ID, NEW.AUTHOR, NEW.TITLE, NEW.CONTENT, NEW.HEADLINE, NEW.FK_EDITOR, NOW());

END//
delimiter ;

delimiter //
CREATE TRIGGER updateArticles
BEFORE UPDATE ON MED_ARTICLES
FOR EACH ROW 
BEGIN

INSERT INTO MED_ARTICLES_H (FK_ARTICLE, AUTHOR, TITLE, CONTENT, HEADLINE, FK_EDITOR, MODIFIED_DATE)
  VALUES(OLD.ID, NEW.AUTHOR, NEW.TITLE, NEW.CONTENT, NEW.HEADLINE, NEW.FK_EDITOR, NOW());

END//
delimiter ;
