delimiter //
CREATE TRIGGER insertNews
AFTER INSERT ON MED_NEWS
FOR EACH ROW 
BEGIN

INSERT INTO MED_NEWS_H (FK_ARTICLE, AUTHOR, TITLE, CONTENT, HEADLINE, FK_EDITOR, MODIFIED_DATE)
  VALUES(NEW.ID, NEW.AUTHOR, NEW.TITLE, NEW.CONTENT, NEW.HEADLINE, NEW.FK_EDITOR, NOW());

END//
delimiter ;

delimiter //
CREATE TRIGGER updateNews
BEFORE UPDATE ON MED_NEWS
FOR EACH ROW 
BEGIN

INSERT INTO MED_NEWS_H (FK_ARTICLE, AUTHOR, TITLE, CONTENT, HEADLINE, FK_EDITOR, MODIFIED_DATE)
  VALUES(OLD.ID, NEW.AUTHOR, NEW.TITLE, NEW.CONTENT, NEW.HEADLINE, NEW.FK_EDITOR, NOW());

END//
delimiter ;