delimiter //
CREATE TRIGGER insertUsers
AFTER INSERT ON MED_USERS
FOR EACH ROW 
BEGIN
IF (SELECT COUNT(*) FROM MED_UNIVERSITIES WHERE NAME=NEW.UNIVERSITY) = 0 THEN
            insert into MED_UNIVERSITIES (NAME) VALUES (NEW.UNIVERSITY);
        END IF;

END//
delimiter ;
