CREATE TABLE MED_ADMINS(
	USERNAME VARCHAR(40) NOT NULL,
	PASSWORD VARCHAR(40) NOT NULL
);

--TODO Michal last login...

ALTER TABLE MED_ADMINS add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

--insert into MED_ADMINS (USERNAME, PASSWORD) VALUES ('michal', 'michal');