CREATE TABLE MED_ARTICLES(
AUTHOR VARCHAR(32) NULL,
TITLE VARCHAR(100) NULL,
CONTENT VARCHAR(3000) NULL, 
HEADLINE VARCHAR(3000) NULL,
FK_EDITOR VARCHAR(10) NULL,
STATUS VARCHAR(1) NULL
);


	--DESCRIPTION	VARCHAR(255) NULL,
	--LAST_MODIFIED DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
	
ALTER TABLE MED_ARTICLES add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

--insert into MED_ARTICLES (AUTHOR, TITLE, CONTENT, HEADLINE) VALUES ('Mikolaj Kopernik', 'O obrotach sfer niebieskich', 'Lorem ipsum', 'Rozprawa naukowa');