CREATE TABLE MED_ARTICLES(
	AUTHOR		VARCHAR(32) NULL,
	TITLE       VARCHAR(32) NULL,
	CONTENT		VARCHAR(3000) NULL, --todo michal bez ograniczen
	HEADLINE		VARCHAR(3000) NULL,
	--DESCRIPTION	VARCHAR(255) NULL,
	--LAST_MODIFIED DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
	FK_EDITOR VARCHAR(10) NULL
);

ALTER TABLE MED_ARTICLES add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

--insert into MED_ARTICLES (AUTHOR, TITLE, CONTENT, HEADLINE) VALUES ('Mikolaj Kopernik', 'O obrotach sfer niebieskich', 'Lorem ipsum', 'Rozprawa naukowa');