CREATE TABLE MED_ENROLMENTS(
	NAME VARCHAR(40) NULL,
	SURNAME VARCHAR(40) NULL,
	DATE DATETIME NULL,
	EMAIL VARCHAR(60) NULL
);

ALTER TABLE MED_ENROLMENTS add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);


--insert into MED_ENROLMENTS (NAME, SURNAME, DATE, EMAIL) VALUES ('Michal', 'Labuda', NOW(), 'michal@o2.pl');