create table MED_EVENTS(
    FROM_DATE DATETIME NOT NULL,
    TO_DATE DATETIME NOT NULL,
    FK_SCHEDULE int not null,
    TITLE varchar(100) NULL,
    DESCRIPTION VARCHAR(300) NULL
 )

ALTER TABLE MED_EVENTS add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);