CREATE TABLE MED_NEWS(
	AUTHOR VARCHAR(32) NULL,
	TITLE VARCHAR(100) NULL,
	CONTENT VARCHAR(3000) NULL, 
	HEADLINE VARCHAR(3000) NULL,
	FK_EDITOR VARCHAR(10) NULL,
	STATUS VARCHAR(1) NULL
);

ALTER TABLE MED_NEWS add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

--insert into MED_NEWS (AUTHOR, TITLE, CONTENT, HEADLINE, FK_EDITOR, STATUS) VALUES ('Michal Lab', 'Nowe wydarzenie', 'Lorem ipsum', 'Warto zobaczyc!', '1', 'A');
