CREATE TABLE MED_UNIVERSITIES(
	NAME VARCHAR(100) NOT NULL
);

ALTER TABLE MED_UNIVERSITIES add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

--insert into MED_UNIVERSITIES (NAME) VALUES ('Uniwersytet Jagiellonski');