CREATE TABLE MED_USERS(
	NAME VARCHAR(40) NOT NULL,
	SURNAME VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	PASSWORD VARCHAR(40) NOT NULL,
	REGISTERDATE DATETIME NULL,
	UNIVERSITY VARCHAR(100) NULL,
	PHONE VARCHAR(20) NULL,
	CONGRESSROLE VARCHAR(5) NULL,
	SUBJECTDESCRIPTION VARCHAR(2000) NULL,
	CONTACTCOMMENTS VARCHAR(300) NULL,
	CONFIRMATION VARCHAR(1) NULL,
	PRIVILEGES VARCHAR(5) NULL,
	SUMMARY BLOB NULL,
	ABSTRACT BLOB NULL,
	PAPER_ACCEPTATION VARCHAR(1) NULL,
	PAYMENT INT NULL,
	PAYMENT_ACCEPTED VARCHAR(1) NULL,
	ACADEMIC_TITLE VARCHAR(5) NULL,
	ACADEMIC_STATUS VARCHAR(5) NULL,
	MASTER VARCHAR(1) NULL,
	ENGINEER VARCHAR(1) NULL,
	FK_EDITOR VARCHAR(10) NULL
);

--TODO Michal last login... updatowany po przeslaniu rows[0]

ALTER TABLE MED_USERS add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

