CREATE TABLE MED_USERS(
	NAME VARCHAR(40) NOT NULL,
	SURNAME VARCHAR(40) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	PASSWORD VARCHAR(40) NOT NULL,
	REGISTERDATE DATETIME NULL,
	UNIVERSITY VARCHAR(100) NOT NULL,
	PHONE VARCHAR(20) NULL,
	CONGRESSROLE VARCHAR(5) NULL,
	SUBJECTDESCRIPTION VARCHAR(2000) NULL,
	CONTACTCOMMENTS VARCHAR(300) NULL,
	CONFIRMATION VARCHAR(1) NULL,
	PRIVILEGES VARCHAR(5) NULL
);

--TODO Michal last login... updatowany po przeslaniu rows[0]

ALTER TABLE MED_USERS add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

