create table MED_WORKSHOPS_USERS(
  FK_USER VARCHAR(10) NULL,
  FK_WORKSHOP VARCHAR(10) NULL
 );
 
 ALTER TABLE MED_WORKSHOPS_USERS add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);